mount: test I/O sanity
samba-in-kubernetes/sit-test-cases pull request #15
Opened 2023-07-25 16:03 UTC by synarete

Add extra I/O checks to mounted SMB share, using different files sizes and number-of-file per directory:

 - Write-read + data consistency check.
 - Overwrite-read + data consistency check.
 - Stat + size check
 - Unlink

Using Pyhton's pathlib over local mount-point.

2023-07-25 17:39 UTC, phlogistonjohn requested changes
Commit message typo: Pyhton

Generally looks OK to me otherwise.

2023-07-25 17:39 UTC, phlogistonjohn commented on testcases/mount/test_mount_io.py
> +        print("Error while executing test_io_consistency: " + str(ex))
Minor taste thing: I generally prefer to see f-strings or `%s` interpolation rather than string concatenation in python code. Seems more idiomatic to me.

2023-07-26 09:19 UTC, synarete commented on testcases/mount/test_mount_io.py
> +        print("Error while executing test_io_consistency: " + str(ex))
Agreed -- will fix.

2023-07-26 09:28 UTC, anoopcs9 commented
@synarete I see the following error from CI [console output](https://jenkins-samba.apps.ocp.cloud.ci.centos.org/job/samba_gluster-integration-test-cases/236/console).
```
==================================== ERRORS ====================================
____________________ ERROR at setup of test_io_consistency _____________________
file /root/samba-integration-tests/testcases/mount/test_mount_io.py, line 117
  def test_io_consistency(rootdir: str) -> None:
E       fixture 'rootdir' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_xml_attribute, record_xml_property, recwarn, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/root/samba-integration-tests/testcases/mount/test_mount_io.py:117
____________________ ERROR at setup of test_io_consistency _____________________
file /root/samba-integration-tests/testcases/mount/test_mount_io.py, line 117
  def test_io_consistency(rootdir: str) -> None:
E       fixture 'rootdir' not found
>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_xml_attribute, record_xml_property, recwarn, tmpdir, tmpdir_factory
>       use 'pytest --fixtures [testpath]' for help on them.

/root/samba-integration-tests/testcases/mount/test_mount_io.py:117
```

2023-07-26 10:59 UTC, synarete commented
> @synarete I see the following error from CI [console output](https://jenkins-samba.apps.ocp.cloud.ci.centos.org/job/samba_gluster-integration-test-cases/236/console).
> 
> ```
> ==================================== ERRORS ====================================
> ____________________ ERROR at setup of test_io_consistency _____________________
> file /root/samba-integration-tests/testcases/mount/test_mount_io.py, line 117
>   def test_io_consistency(rootdir: str) -> None:
> E       fixture 'rootdir' not found
> >       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_xml_attribute, record_xml_property, recwarn, tmpdir, tmpdir_factory
> >       use 'pytest --fixtures [testpath]' for help on them.
> 
> /root/samba-integration-tests/testcases/mount/test_mount_io.py:117
> ____________________ ERROR at setup of test_io_consistency _____________________
> file /root/samba-integration-tests/testcases/mount/test_mount_io.py, line 117
>   def test_io_consistency(rootdir: str) -> None:
> E       fixture 'rootdir' not found
> >       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_xml_attribute, record_xml_property, recwarn, tmpdir, tmpdir_factory
> >       use 'pytest --fixtures [testpath]' for help on them.
> 
> /root/samba-integration-tests/testcases/mount/test_mount_io.py:117
> ```

@anoopcs9 I pushed (force) a fix, but apparently current failure is not related to this PR. Could you please take a look?

2023-07-26 11:13 UTC, anoopcs9 commented
> > @synarete I see the following error from CI [console output](https://jenkins-samba.apps.ocp.cloud.ci.centos.org/job/samba_gluster-integration-test-cases/236/console).
> > ```
> > ==================================== ERRORS ====================================
> > ____________________ ERROR at setup of test_io_consistency _____________________
> > file /root/samba-integration-tests/testcases/mount/test_mount_io.py, line 117
> >   def test_io_consistency(rootdir: str) -> None:
> > E       fixture 'rootdir' not found
> > >       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_xml_attribute, record_xml_property, recwarn, tmpdir, tmpdir_factory
> > >       use 'pytest --fixtures [testpath]' for help on them.
> > 
> > /root/samba-integration-tests/testcases/mount/test_mount_io.py:117
> > ____________________ ERROR at setup of test_io_consistency _____________________
> > file /root/samba-integration-tests/testcases/mount/test_mount_io.py, line 117
> >   def test_io_consistency(rootdir: str) -> None:
> > E       fixture 'rootdir' not found
> > >       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_xml_attribute, record_xml_property, recwarn, tmpdir, tmpdir_factory
> > >       use 'pytest --fixtures [testpath]' for help on them.
> > 
> > /root/samba-integration-tests/testcases/mount/test_mount_io.py:117
> > ```
> 
> @anoopcs9 I pushed (force) a fix, but apparently current failure is not related to this PR. Could you please take a look?

Sure, I'll re-trigger once the issue(with reserving node) in CentOS CI is fixed.

2023-07-28 06:05 UTC, anoopcs9 requested changes
@synarete Test run couldn't complete due to total timeout of 6hrs. I foresee a problem with newly introduced test cases.

2023-07-28 06:05 UTC, anoopcs9 commented on testcases/mount/test_mount_io.py
> +        _run_test(_make_datasets(base, 1024, 10000))
Creation of large number of small files via SMB on GlusterFS through Samba(with new VFS) takes much longer time than our expectation(see this [slide](https://sambaxp.org/fileadmin/user_upload/sambaxp2023-Slides/CS_sXP23_DFSvianewVFS.pdf#page=15) from my sambaXP presentation). It can be worse with type of GlusterFS volume used(distribute-replicate, distribute-disperse etc..). Thus we may have to reduce the number of files used for small file creation(may be 1000?).

2023-07-28 12:10 UTC, synarete commented on testcases/mount/test_mount_io.py
> +        _run_test(_make_datasets(base, 1024, 10000))
Changed to 500 files

2023-07-31 07:39 UTC, synarete commented
> @synarete Test run couldn't complete due to total timeout of 6 hours. I foresee a problem with newly introduced test cases.

@anoopcs9 Could you please re-start the CI with new fix (up to 500 files)?

2023-07-31 09:10 UTC, anoopcs9 commented
> > @synarete Test run couldn't complete due to total timeout of 6 hours. I foresee a problem with newly introduced test cases.
> 
> @anoopcs9 Could you please re-start the CI with new fix (up to 500 files)?

CentOS CI runs are automatically triggered for any updates in the PR branch. Error listed in https://github.com/samba-in-kubernetes/sit-test-cases/pull/15#issuecomment-1651351312 is still seen with an additional `Bad file descriptor` error. I haven't checked further.

"Details" link towards the right hand side of the **centos-ci/glusterfs/devel** check from the list of GitHub checks will take you to jenkins where you can see the test run results from "Console Output" option.

2023-08-01 06:37 UTC, anoopcs9 commented
> > @synarete Test run couldn't complete due to total timeout of 6 hours. I foresee a problem with newly introduced test cases.
> 
> @anoopcs9 Could you please re-start the CI with new fix (up to 500 files)?

Error from https://github.com/samba-in-kubernetes/sit-test-cases/pull/15#issuecomment-1651351312 is no longer present with the latest run. I am inclined to believe its a GlusterFS problem based on the following output:

```
=================================== FAILURES ===================================
__________________________________ test_mount __________________________________

    def test_mount() -> None:
        test_info_file = os.getenv("TEST_INFO_FILE")
        if test_info_file:
            test_info = testhelper.read_yaml(test_info_file)
>           mount_test(test_info)

testcases/mount/test_mount.py:56: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
testcases/mount/test_mount.py:37: in mount_test
    check_io_consistency(mount_point)
testcases/mount/mount_io.py:145: in check_io_consistency
    _check_io_consistency(rootdir)
testcases/mount/mount_io.py:128: in _check_io_consistency
    _run_checks(_make_datasets(base, 1024, 100))
testcases/mount/mount_io.py:101: in _run_checks
    dset.write()
testcases/mount/mount_io.py:22: in write
    self.path.write_bytes(self.data)
/usr/lib64/python3.6/pathlib.py:1205: in write_bytes
    with self.open(mode='wb') as f:
/usr/lib64/python3.6/pathlib.py:1183: in open
    opener=self._opener)
/usr/lib64/python3.6/pathlib.py:1037: in _opener
    return self._accessor.open(self, flags, mode)
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

pathobj = PosixPath('/tmp/54748/mnt_0/test_io_consistency/32')
args = (524865, 438)

    @functools.wraps(strfunc)
    def wrapped(pathobj, *args):
>       return strfunc(str(pathobj), *args)
E       BlockingIOError: [Errno 11] Resource temporarily unavailable: '/tmp/54748/mnt_0/test_io_consistency/32'

/usr/lib64/python3.6/pathlib.py:387: BlockingIOError
----------------------------- Captured stdout call -----------------------------


Testing //192.168.123.10/gluster-vol-replicate


Testing //192.168.123.10/gluster-vol-disperse


Error while executing test_io_consistency: %s [Errno 11] Resource temporarily unavailable: '/tmp/54748/mnt_0/test_io_consistency/32'
Error while executing test
```

@spuiuk Did I get it right that _test_mount_ failed only with disperse volume?

2023-08-01 07:11 UTC, synarete commented
> > > @synarete Test run couldn't complete due to total timeout of 6 hours. I foresee a problem with newly introduced test cases.
> > 
> > 
> > @anoopcs9 Could you please re-start the CI with new fix (up to 500 files)?
> 
> Error from [#15 (comment)](https://github.com/samba-in-kubernetes/sit-test-cases/pull/15#issuecomment-1651351312) is no longer present with the latest run. I am inclined to believe its a GlusterFS problem based on the following output:
> 
> ```
> =================================== FAILURES ===================================
> __________________________________ test_mount __________________________________
> 
>     def test_mount() -> None:
>         test_info_file = os.getenv("TEST_INFO_FILE")
>         if test_info_file:
>             test_info = testhelper.read_yaml(test_info_file)
> >           mount_test(test_info)
> 
> testcases/mount/test_mount.py:56: 
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> testcases/mount/test_mount.py:37: in mount_test
>     check_io_consistency(mount_point)
> testcases/mount/mount_io.py:145: in check_io_consistency
>     _check_io_consistency(rootdir)
> testcases/mount/mount_io.py:128: in _check_io_consistency
>     _run_checks(_make_datasets(base, 1024, 100))
> testcases/mount/mount_io.py:101: in _run_checks
>     dset.write()
> testcases/mount/mount_io.py:22: in write
>     self.path.write_bytes(self.data)
> /usr/lib64/python3.6/pathlib.py:1205: in write_bytes
>     with self.open(mode='wb') as f:
> /usr/lib64/python3.6/pathlib.py:1183: in open
>     opener=self._opener)
> /usr/lib64/python3.6/pathlib.py:1037: in _opener
>     return self._accessor.open(self, flags, mode)
> _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
> 
> pathobj = PosixPath('/tmp/54748/mnt_0/test_io_consistency/32')
> args = (524865, 438)
> 
>     @functools.wraps(strfunc)
>     def wrapped(pathobj, *args):
> >       return strfunc(str(pathobj), *args)
> E       BlockingIOError: [Errno 11] Resource temporarily unavailable: '/tmp/54748/mnt_0/test_io_consistency/32'
> 
> /usr/lib64/python3.6/pathlib.py:387: BlockingIOError
> ----------------------------- Captured stdout call -----------------------------
> 
> 
> Testing //192.168.123.10/gluster-vol-replicate
> 
> 
> Testing //192.168.123.10/gluster-vol-disperse
> 
> 
> Error while executing test_io_consistency: %s [Errno 11] Resource temporarily unavailable: '/tmp/54748/mnt_0/test_io_consistency/32'
> Error while executing test
> ```
> 
> @spuiuk Did I get it right that _test_mount_ failed only with disperse volume?

@anoopcs9 @spuiuk Your help is need to understand this failure: I reordered the tests:
 1) Single-file 4K IO -- OK
 2) Single-file 16M IO -- OK
 3) 10-files 1M IO -- OK
 3) 100-files 1K IO -- Failed with `errno 11`

Any idea why?

2023-08-01 22:11 UTC, spuiuk commented
@synarete, I was in two minds about deleting this test because it didn't do anything which the consistency test wasn't also doing. This meant that I didn't parameterize it like I did the other tests. Since we changed the consistency test to use smbclient, this is now the only test at the moment which uses cifs_mount so it is useful.
However before you make any changes to this test to add this new testing, can you parameterize it. I've already written the code in 
https://github.com/spuiuk/sit-test-cases/commit/a12736d973cb4926b49fccdd3e38b7730ccca124
Please pull this patch to the top of your set of commits. This will result in far better reporting.
 
@anoopcs9 @xhernandez, With the new PRs to centos-ci where the nightly run is now run on the sit-environment repository, maybe we should modify the CI tests for sit-test-cases to use a local samba server with the share on the local filesystem. This will make the CI runs for sit-test-cases complete quickly and only the nightly tests will run on the full test environment of glusterfs and xfs. Also no more failures caused by glusterfs.

As we see from the CI run. This passes on xfs but fails on glusterfs. This is obviously a problem with glusterfs. The next step should be to write a simpler reproducer which will make for easier reproducing.

2023-08-02 05:25 UTC, anoopcs9 commented
> @anoopcs9 @xhernandez, With the new PRs to centos-ci where the nightly run is now run on the sit-environment repository,

Currently full run is configured for sit-test-cases repository(PR and nightly run).

> maybe we should modify the CI tests for sit-test-cases to use a local samba server with the share on the local filesystem. This will make the CI runs for sit-test-cases complete quickly and only the nightly tests will run on the full test environment of glusterfs and xfs. Also no more failures caused by glusterfs.

I would like to keep running both(glusterfs and xfs) for a little longer. I've also made **centos-ci/glusterfs** check optional.

2023-08-02 06:25 UTC, anoopcs9 commented
> It really seems to be failing for disperse volumes only, which seems to point to some Gluster related issue. Without more logs I can't tell for sure. I'll try to reproduce it locally and see what happens.
> 
> Given that this seems a very simple test, it's weird that it fails. Thinking about it, one possibility that came to my mind is that it could be caused by a memory issue. The servers are configured with just 1 GiB of memory, and disperse volumes are more cpu and memory hungry than replicated ones. Maybe it's not related, but it's the only explanation I can give for now.

Our CentOS CI nodes are beefy enough to get the memory increased as per our requirements. Feel free to suggest after RCA 😊 .

> Besides that, maybe we should only consider the result of an execution on top of XFS to decide for correctness, and leave the Gluster-based test just for reference.

XFS integration test results are now configured to run and report status as **centos-ci/xfs**.

2023-08-02 09:12 UTC, synarete commented
> > > It really seems to be failing for disperse volumes only, which seems to point to some Gluster related issue. Without more logs I can't tell for sure. I'll try to reproduce it locally and see what happens.
> > > Given that this seems a very simple test, it's weird that it fails. Thinking about it, one possibility that came to my mind is that it could be caused by a memory issue. The servers are configured with just 1 GiB of memory, and disperse volumes are more cpu and memory hungry than replicated ones. Maybe it's not related, but it's the only explanation I can give for now.
> > 
> > 
> > Our CentOS CI nodes are beefy enough to get the memory increased as per our requirements. Feel free to suggest after RCA blush .
> 
> I've taken a look and I've been able to reproduce a similar problem, but not exactly the same. In my case the failure also happens in the disperse volume, during an "open" operation, but the error I get is "Bad file descriptor" instead of "Resource temporarily unavailable". I can see in the logs that the error comes clearly from Gluster, but there's no indication of a memory issue.
> 
> Since now we are using XFS as the reference test, I'll investigate this further but after completing some other work.

@xhernandez Many thanks for this input. The motivation behind this PR is to do synthetic (and rather trivial) I/O in order to find simple-to-analyze failures, before executing more complex framworks (such as `xfstests` or `fio`). And indeed, it appears that it served its purpose.

2023-08-02 11:36 UTC, spuiuk commented
The output looks much better with the parmeterized pytest output. Just one small suggestion. The original mount test mounted the filesystem and created a file onto the share to ensure that the test can write to the file. This second part of writing to the filesystem is no longer needed as your testing now does this and more. So I would remove the old file writing test from the mount test.

2023-08-02 11:45 UTC, synarete commented
> The output looks much better with the parmeterized pytest output. Just one small suggestion. The original mount test mounted the filesystem and created a file onto the share to ensure that the test can write to the file. This second part of writing to the filesystem is no longer needed as your testing now does this and more. So I would remove the old file writing test from the mount test.

Fair enough. Will remove it.

2023-08-03 13:17 UTC, spuiuk reviewed
ACK. 

The test can probably be modified further to take advantage of the pytest framework. In the current form it is sufficient and provides a useful service.

It has already found a bug in the gluster-disperse volume - It is already working!

2023-08-03 13:18 UTC, spuiuk approved these changes

2023-08-03 17:28 UTC, phlogistonjohn requested changes
It's mostly OK, and with light arm twisting I'd be OK to approve, but there's one method I think I'd prefer to see changed first.

I also am wondering about how to make these actions more visible to the pytest level and not simply embedded within another test. However, I am OK with taking the changes and iterating on them later.

2023-08-03 17:28 UTC, phlogistonjohn commented on testcases/mount/mount_io.py
> +    def generate_prandom_bytes(size: int) -> bytes:
First, I prefer not to see staticmethods when a regular function will suffice. It's hard to tell if a staticmethod exists to serve some api/interface or not. If this function is not to be used outside of the class/file make it a "_" prefixed name. Then there's no "namespace pollution".  I'm not the only one who [objects to staticmethod](https://www.seporaitis.net/posts/2020/05/05/python-staticmethod-usage/)...  as the linked post notes, GvR has called staticmethod a somewhat mistake.

Second, this can be followed up on later: it might be good to ensure that the code can also be reproduced in the case a particular pattern triggers an issue. I haven't double checked if there's a global random seed that affects this. If not we should make sure to do it ourselves.

Also, is `prandom` intentional or a typo?

2023-08-03 17:28 UTC, phlogistonjohn commented on testcases/mount/mount_io.py
> +def _reset_random_seed() -> None:
See my comment above. We should see if pytest provides any random seed management, and if not do some of our own.

2023-08-06 12:58 UTC, synarete commented on testcases/mount/mount_io.py
> +def _reset_random_seed() -> None:
We should probably use [pytest-randomly](https://pypi.org/project/pytest-randomly) but better add it in a separate PR.

2023-08-07 07:33 UTC, anoopcs9 approved these changes
As discussed earlier, GlusterFS test results still fail with `EBADF`/`EAGAIN` on disperse volumes. But for now let's move forward.

2023-08-07 17:36 UTC, phlogistonjohn approved these changes
LGTM, thanks

2023-08-08 11:07 UTC, spuiuk approved these changes
ACK

2023-08-08 11:07 UTC, merged