README.md: Add details on how the tests are run
samba-in-kubernetes/sit-test-cases pull request #20
Opened 2023-08-09 15:17 UTC by Shwetha-Acharya

Fixes: #19

2023-08-17 14:09 UTC, phlogistonjohn commented on README.md
> +This repo contains tests for Samba and storage integration that are run on the client machines.
Perhaps we can be a bit clearer here what storage integration means. Something like: "This repo contains tests for Samba when used with Clustered or other Software-Defined Storage systems"... ?

2023-08-17 14:10 UTC, phlogistonjohn commented on README.md
> +## We can also manually run the individual tests in sit-environment on our local machines using the following steps:
I'm being nitpicky, but this seems a bit long for a title.

2023-08-17 14:16 UTC, phlogistonjohn commented on README.md
> +- After installation, sit-envornment should be setup using [setup guide](https://github.com/samba-in-kubernetes/sit-environment/blob/main/docs/Fedora-Setup.md)
Typo: `sit-envornment`

When used as a verb it is more grammatical to spell "set up" as two words. It's typically spelled as one word only when you use it as a noun.

2023-08-17 14:16 UTC, phlogistonjohn commented on README.md
> +- Login to client0 inorder the manually run the tests on the client
More nitpicks: "Log in" and "in order to"

2023-08-17 14:16 UTC, phlogistonjohn commented on README.md
> +      # sudo -i
Why does this need to run as root?  If we can' avoid it (for now), can we avoid using a root shell and just run `sudo <my particular command>` instead?

2023-08-21 11:22 UTC, Shwetha-Acharya commented on README.md
> +      # sudo -i
I have updated this PR as per all other suggestions of yours, expect this thread. Adding other reviewers as well, so that we can get collective opinion on this. Please pitch in if you have any views on my last comment @phlogistonjohn

2023-08-21 11:47 UTC, phlogistonjohn commented on README.md
> +      # sudo -i
It's fine for now. You're trying to document how it works not how it should be after all.

2023-08-21 12:47 UTC, synarete reviewed
Looks fine, but see style comments

2023-08-21 12:47 UTC, synarete commented on README.md
> +This repo contains tests for Samba when used with Clustered or other Software-Defined Storage systems.
Consider changing to: "when used with clustered file-system, such as fephfs, glusterfs or other".

2023-08-21 12:47 UTC, synarete commented on README.md
> +[sit-environment](https://github.com/samba-in-kubernetes/sit-environment) creates an environment on which these tests can be run using vagrant by setting up
In most README.md files we try to limit to 80-chars lines. Some of use still `vim` on terminal with large fonts...

2023-08-21 12:47 UTC, synarete commented on README.md
> +PRE-REQUISITES:
Why not: ```### Prerequisites:```

2023-08-21 12:47 UTC, synarete commented on README.md
> +STEPS TO RUN INDIVIDUAL SIT TEST CASES:
Why not: ```### Run individual test-cases:```

2023-08-21 13:15 UTC, Shwetha-Acharya commented on README.md
> +[sit-environment](https://github.com/samba-in-kubernetes/sit-environment) creates an environment on which these tests can be run using vagrant by setting up
I had now limited all the lines to 80 charecters, except for the link in line 21, which on splitting does not behave as link anymore in .md @synarete

2023-08-21 15:21 UTC, obnoxxx commented on README.md
> -This branch contains the actual tests for the cluster nodes and are run on the client machines.
branch --> repository

2023-08-21 15:22 UTC, obnoxxx commented on README.md
> +creates an environment on which these tests can be run. Environment is created
```suggestion
creates an environment on which these tests can be run.  The environment is created
```

2023-08-21 15:28 UTC, obnoxxx commented on README.md
> +using vagrant by setting up virtual machines with the desired backend storage,
```suggestion
on  virtual machines that are set up  by vagrant and then configured with the desired backend storage,
```

2023-08-21 15:34 UTC, obnoxxx commented on README.md
> +using vagrant by setting up virtual machines with the desired backend storage,
I do in fact doubt that this level of detail is right in the  test-cases repo docs: it is information that should be in the sit-environment docs.

2023-08-22 06:12 UTC, Shwetha-Acharya commented on README.md
> +using vagrant by setting up virtual machines with the desired backend storage,
@obnoxxx done!

2023-08-22 11:21 UTC, spuiuk commented
Hello Shwetha,

Thanks for expanding on this README. This will help new users start out with the sit-test-cases repo and has been required for a while.

My comments are with respect to the sit-environment. While it started out as test cases to be run against the test environment which was setup with sit-environment, we do not have any reason to limit testing to that environment. sit-test-cases is designed to work against any SMB server and will work equally well against a locally running samba server.

I think instead of describing how to setup a sit-environment test infrastructure which requires a lot of resources, we should aim for the easiest option and describe testing against a local SMB server without going into much detail about setting up a Samba server. ie. we should start out with asking the user to have a working SMB server to test against and then proceed to setting up the test-info.yml and running the tests.

We can provide more information for sit-test-cases on sit-environment by either modifying an existing doc or creating a new one in https://github.com/samba-in-kubernetes/sit-environment/tree/main/docs

2023-08-22 14:36 UTC, Shwetha-Acharya commented
> Hello Shwetha,
> 
> Thanks for expanding on this README. This will help new users start out with the sit-test-cases repo and has been required for a while.
> 
> My comments are with respect to the sit-environment. While it started out as test cases to be run against the test environment which was setup with sit-environment, we do not have any reason to limit testing to that environment. sit-test-cases is designed to work against any SMB server and will work equally well against a locally running samba server.
> 
> I think instead of describing how to setup a sit-environment test infrastructure which requires a lot of resources, we should aim for the easiest option and describe testing against a local SMB server without going into much detail about setting up a Samba server. ie. we should start out with asking the user to have a working SMB server to test against and then proceed to setting up the test-info.yml and running the tests.
> 
> We can provide more information for sit-test-cases on sit-environment by either modifying an existing doc or creating a new one in https://github.com/samba-in-kubernetes/sit-environment/tree/main/docs

I was just wondering if it was good idea to add another option of directly using these tests on already created samba setup in sit-test-cases README.md itself?
If we provide two options,  one who does not have samba setup already created can use the automation provided by sit-environment.
I had also not mentioned about already existing samba setup in this doc, as it requires manual efforts. My priority was automation.
But now I agree to your point about the additional resource utilization.

I felt it was necessary to add information in this README.md file because in [sit-environment](https://github.com/samba-in-kubernetes/sit-environment), we are already indicating about sit-test-cases repo. 

As sit-test-cases is an individual repo, don't you think adding complete detail here makes it much useful?
Also as a newbie when I had installed this sit-test-cases repo, I was hoping to know about it with the help of README file. However, found the few lines in the existing file not much useful.

Please let me know if you think otherwise @spuiuk

2023-08-23 15:59 UTC, spuiuk commented
I agree that it is important to add information on how to use the repository. Since you are new to this project, your perspective on how best to present this is welcome.

I am assuming that users of this project will already have a SMB server available and would like to run their tests on them. I think it would be very useful if we just get to the point and help users get up and running with sit-test-cases.

We can add a doc on setting up a basic samba server setup for a devel environment for users who want to contribute to the sit-test-cases.

2023-09-14 09:40 UTC, spuiuk requested changes

2023-09-14 09:40 UTC, spuiuk commented on README.md
> +- Export essential PATH variables inorder to access pytest and test-info.yml:
We can simply use the Makefile to do all the testing. 

The targets we are interested in are 
test - which runs the complete test suite
and sanity_test - a quick test to confirm that the smb server is accessible.

To run individual tests, I would simply use the command in the following manner from the root of the sit-test-cases repo
```
PYTHONPATH=`pwd` TESTINFO_FILE=test-info.yml pytest -v testcases/smbtorture
```

2023-09-14 09:40 UTC, spuiuk commented on README.md
> +
We don't really need a CTDB with clustered samba installed. I recommend that we change it to something similar to
```
The tests are part of the Samba Integrated testing project which is primarily used to test Samba servers exporting a clustered filesystem. 

The tests itself are designed to be run against any SMB server. The only prerequisites are that we have a SMB server exporting a filesystem which can be accessed over the network.

```

2023-09-14 11:55 UTC, Shwetha-Acharya commented on README.md
> +
If there is any doc about exporting the filesystem, we can add it too here.
@spuiuk Are you aware of any such relevant doc?

2023-09-18 07:00 UTC, anoopcs9 requested changes

2023-09-19 06:19 UTC, anoopcs9 commented on README.md
> +filesystem such as cephfs, glusterfs and others.
My bad. Withdrawing the above suggestion.

2023-09-19 06:54 UTC, anoopcs9 approved these changes

2023-09-20 11:58 UTC, spuiuk requested changes

2023-09-20 11:58 UTC, spuiuk commented on README.md
> +      #PYTHONPATH=`pwd` TESTINFO_FILE=test-info.yml pytest -v testcases/smbtorture
a space between the '#' and PYTHONPATH please. 

also, can you please mention that some tests require you to mount the filesystem using the cifs kernel module and you may need to run the tests as root.

It looks fine otherwise.

2023-09-21 09:35 UTC, anoopcs9 requested changes

2023-09-21 09:35 UTC, anoopcs9 commented on README.md
> +- Mount the filesystem using cifs kernal module to run the tests that use cifs
```suggestion
- Mount the filesystem using cifs kernel module to run the tests that use cifs
```

2023-09-21 11:43 UTC, spuiuk requested changes

2023-09-21 11:43 UTC, spuiuk commented on README.md
> +  $ make test
make test run the entire test suite. I would not use this as a sanity test
make sanity_test runs just the sanity test to confirm that the SMB server is working as expected and ready for the full test suite.

The individual tests below is just to run specific tests and  should not be the default step to run. We only run that when we are testing to fix an individual test case.

2023-09-21 11:43 UTC, spuiuk commented on README.md
> +      $ make test
make test runs the full test suite. This is not a sanity test

make sanity_test runs the actual sanity test which confirms that the smb server can be accessed and is ready to perform the full test on.

2023-09-21 11:43 UTC, spuiuk commented on README.md
> +      # PYTHONPATH=`pwd` TESTINFO_FILE=test-info.yml pytest -v testcases/smbtorture
I only use this when I need to run a specific test. This is usually when I am working on fixing a particular problem. So this is an exception and shouldn't be needed as a rule. This however still needs to be documented in case the user wants to run a particular test.

2023-09-21 11:43 UTC, spuiuk commented on README.md
> +- Mount the filesystem using cifs kernel module to run the tests that use cifs
would rewrite this part.

Some tests are performed against a share mounted using the cifs kernel module. This particular action requires root access.

2023-09-21 11:43 UTC, spuiuk commented on README.md
> +  test_mount.py and test_consistency.py are few such tests that use cifs share.
test_consistency uses smbclient to connect to the server to perform a sanity test. This doesn't actually use the cifs  mount.

2023-09-24 09:08 UTC, synarete reviewed
Looks fine, but require finial polish.

2023-09-24 09:08 UTC, synarete commented on README.md
> +- Install sit-cases
Install sit-test-cases

2023-09-24 09:08 UTC, synarete commented on README.md
> +- The tests are to be run as root.
Tests must be run as root

2023-09-25 12:15 UTC, spuiuk requested changes

2023-09-25 12:15 UTC, spuiuk commented on README.md
> +- Run an indivisual test case (can be used for debugging):
spelling. "individual". Also please can you specify that the command has to be run in the root of the repo. The PYTHONPATH=`pwd` sets the search path of the library to the root of the repo where we can find the testhelper folder.

2023-09-26 10:36 UTC, spuiuk approved these changes
ACK. Thanks for updating the README file.

2023-09-26 10:41 UTC, spuiuk commented
we have a new failure which doesn't seem to have been caused by the change in this PR but we need to fix this ASAP.

From the failed xfs test.
```
_______________ ERROR collecting testcases/mount/test_mount.py ________________
ImportError while importing test module '/root/sit-test-cases/testcases/mount/test_mount.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
.tox/pytest/lib64/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
testcases/mount/test_mount.py:6: in <module>
    import testhelper
E   ModuleNotFoundError: No module named 'testhelper'
__________ ERROR collecting testcases/consistency/test_consistency.py __________
ImportError while importing test module '/root/sit-test-cases/testcases/consistency/test_consistency.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
.tox/pytest/lib64/python3.6/importlib/__init__.py:126: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
testcases/consistency/test_consistency.py:9: in <module>
    import testhelper
E   ModuleNotFoundError: No module named 'testhelper'
```

2023-09-26 13:10 UTC, spuiuk commented
Just checked the CI run from last night.  This passed successfully.
https://jenkins-samba.apps.ocp.cloud.ci.centos.org/job/samba_xfs-integration-test-cases/135/console

Not sure what is causing this new failure.

2023-09-26 13:26 UTC, spuiuk commented
/retest all

2023-09-27 08:32 UTC, spuiuk commented
Shwetha,  It looks like your patch is deleting the empty file conftest.py. This is causing issues with the tox running the test and it doesn't seem to accept the PYTHONPATH variable. Can you please fix this as the test is failing.

2023-10-03 06:06 UTC, Shwetha-Acharya commented
> Shwetha, It looks like your patch is deleting the empty file conftest.py. This is causing issues with the tox running the test and it doesn't seem to accept the PYTHONPATH variable. Can you please fix this as the test is failing.
> 
> I get past this problem on my local test machine by simply creating an empty file conftest.py.

Done!

2023-10-03 10:54 UTC, spuiuk commented
@anoopcs9  @obnoxxx @synarete @phlogistonjohn can you please take one more look at this PR.

2023-10-03 11:29 UTC, anoopcs9 approved these changes

2023-10-03 13:43 UTC, phlogistonjohn approved these changes
Works for me.

2023-10-05 15:16 UTC, merged