Introduce setup and teardown fixtures
samba-in-kubernetes/sit-test-cases pull request #38
Opened 2023-10-13 08:29 UTC by Shwetha-Acharya

With this change, multiple test modules triggered from testcases/mount can be run as individual tests complying to pytest standards. Also any number of new tests can be added efficiently on the mount.

Fixes: #30

2023-10-13 09:12 UTC, Shwetha-Acharya commented
This PR need  changes to be merged to pass the tests

2023-10-13 09:19 UTC, anoopcs9 commented
> This PR need few changes to be merged to pass the tests

Please feel free to edit the description to add the keyword `depends on #<PR.no>` so that its visible in the list of checks.

2023-10-13 11:17 UTC, Shwetha-Acharya commented
> > This PR need few changes to be merged to pass the tests
> 
> Please feel free to edit the description to add the keyword `depends on #<PR.no>` so that its visible in the list of checks.

yes sure, I am still working on a change, will update once I push it

2023-10-25 10:25 UTC, anoopcs9 commented
**centos-ci/xfs** seems to have failed . @Shwetha-Acharya can you check if its related to the proposed change?

2023-10-25 11:27 UTC, spuiuk requested changes

2023-10-25 11:27 UTC, spuiuk commented on conftest.py
> +test_info = os.getenv("TEST_INFO_FILE")
change name to test_info_file for consistency.

2023-10-25 11:27 UTC, spuiuk commented on conftest.py
> +def setup_mount(ipaddr: str, sharename: str) -> str:
Do these have to go into conftest.py instead of within test_mount itself?

2023-10-25 11:47 UTC, Shwetha-Acharya commented on conftest.py
> +def setup_mount(ipaddr: str, sharename: str) -> str:
My idea was to define the fixtures inside conftest.py in reference with the common practice.
These fixtures can then be called inside any tests.

2023-10-26 14:12 UTC, spuiuk commented
The xfs tests are failing
```
testcases/mount/test_mount_dbm.py::test_check_dbm_consistency[192.168.123.10-share-xfs-default] FAILED [ 96%]
testcases/mount/test_mount_io.py::test_check_io_consistency[192.168.123.10-share-xfs-default] ERROR [100%]

...
E           Exception: Setup failed: Error mounting: ret 256 cmd: mount -t cifs -o username=test1,password=x //[192.168.123.10/share-xfs-default](http://192.168.123.10/share-xfs-default) /tmp//10073/mnt_0

conftest.py:32: Exception
---------------------------- Captured stderr setup -----------------------------
Couldn't chdir to /tmp//10073/mnt_0: No such file or directory

```

I believe that this is happening because of the teardown_mount() call by the first test. That deletes the temporary directory which was created for the test. 

in conftest.py
```
tmp_root = testhelper.get_tmp_root()
mount_point = testhelper.get_tmp_mount_point(tmp_root)
```
will be called only once.

you should either create mount/unmount only once for the entire test or fetch a new tmp_root for every test.

2023-11-03 09:47 UTC, Shwetha-Acharya commented
/retest all

2023-11-08 14:07 UTC, spuiuk commented
/retest all

2023-11-08 17:12 UTC, spuiuk commented
/retest centos-ci/xfs

2023-11-08 17:44 UTC, Shwetha-Acharya commented
/retest centos-ci/xfs

2023-11-09 08:09 UTC, Shwetha-Acharya commented
/retest centos-ci/xfs

2023-11-09 08:56 UTC, Shwetha-Acharya commented
/retest all

2023-11-09 14:23 UTC, Shwetha-Acharya commented
/retest all

2023-11-09 17:28 UTC, Shwetha-Acharya commented
@spuiuk regarding your proposal for removal of some helper functions and that change affecting this PR, I definetly agree there is much more scope for refactoring.

But I propose to keep the PRs independent, and small as possible (mostly addressing one issue)
I propose taking this PR and working on other changes with next PR.

2023-11-13 14:18 UTC, spuiuk requested changes

2023-11-13 14:18 UTC, spuiuk commented on conftest.py
> +#!/usr/bin/env python3
Can you please move this into the testcases/mount directory for this particular commit. If we do need this in the future, we can move it to a central location.

2023-11-13 14:18 UTC, spuiuk commented on testcases/consistency/test_consistency.py
> +    "ipaddr,share_name", testhelper.generate_mount_check(test_info_file)
I am not comfortable about moving this pytest parameterize function to a central library. Maybe somewhere which can be included in this test folder itself?

2023-11-13 14:18 UTC, spuiuk commented on testcases/consistency/test_consistency.py
> +test_info_file = os.getenv("TEST_INFO_FILE")
The convention I have tried to follow in later PRs is
test_info_file -> The filename to be used to read the test_info
test_info -> dict containing the information required to run the test.

Can you please stick to this convention. That will also reduce the large number of changes we see in these commits.

2023-11-13 14:18 UTC, spuiuk commented on testcases/consistency/test_consistency.py
> +    "ipaddr,share_name", testhelper.generate_mount_check(test_info_file)
This will also reduce the scope of these commit to just this test instead of also touching consistency and smbtorture tests. We can consider a helper function later and merge it through a separate PR.

2023-11-13 14:18 UTC, spuiuk commented on conftest.py
> +    return test_dir
Will this code below the return be executed?

2023-11-13 14:18 UTC, spuiuk commented on testcases/mount/test_mount_dbm.py
> +    ipaddr: str, sharename: str, setup_mount: str
The parameterize function returns two arguments as we did in the older version. 
But we also see a third argument here which is to trigger the mount function. Does this work?

2023-11-13 15:07 UTC, spuiuk commented on conftest.py
> +    return test_dir
Should you instead use yield in the setup function?
https://docs.pytest.org/en/latest/how-to/fixtures.html#teardown-cleanup-aka-fixture-finalization

2023-11-13 15:22 UTC, spuiuk commented on testcases/mount/test_mount_dbm.py
> +    ipaddr: str, sharename: str, setup_mount: str
I have confirmed that this works fine.

2023-11-13 15:59 UTC, Shwetha-Acharya commented on testcases/consistency/test_consistency.py
> +test_info_file = os.getenv("TEST_INFO_FILE")
yes, I can do it

2023-11-13 16:01 UTC, Shwetha-Acharya commented on testcases/consistency/test_consistency.py
> +    "ipaddr,share_name", testhelper.generate_mount_check(test_info_file)
> I am not comfortable about moving this pytest parameterize function to a central library. Maybe somewhere which can be included in this test folder itself?

Any reason behind it? 
I just thought there were exactly same functions with different names in test as well as in central library. So had thought of reusing the same code.

2023-11-14 06:29 UTC, Shwetha-Acharya commented on testcases/mount/test_mount_dbm.py
> +    ipaddr: str, sharename: str, setup_mount: str
yes, it works as setup_mount is a fixture

2023-11-14 16:05 UTC, spuiuk commented on testcases/consistency/test_consistency.py
> +    "ipaddr,share_name", testhelper.generate_mount_check(test_info_file)
Having given it some more thought. I think I now prefer your approach. Maybe name the call 
testhelper.get_ipaddr_sharename(test_info) 
to match the other calls in testhelper. Similarly for premounted shares, simply use the already existing
testhelper.get_premounted_shares(test_info)

2023-11-14 16:23 UTC, Shwetha-Acharya commented on testcases/consistency/test_consistency.py
> +    "ipaddr,share_name", testhelper.generate_mount_check(test_info_file)
I will update that with next rebase

2023-11-14 17:56 UTC, spuiuk commented on conftest.py
> +test_info = os.getenv("TEST_INFO_FILE")
Please ignore this as discussed. This issue has been handled in an other PR.

2023-11-14 21:04 UTC, spuiuk commented on testcases/consistency/test_consistency.py
> +    "ipaddr,share_name", testhelper.generate_mount_check(test_info_file)
Sorry Shwetha, I've had to unresolve this particular change request. 

I was looking at the test output of cephfs test for a different PR
```
testcases/consistency/test_consistency.py::test_consistency[192.168.123.10-share-cephfs-default] PASSED [ 78%]
testcases/consistency/test_consistency.py::test_consistency[192.168.123.11-share-cephfs-default] PASSED [ 81%]
testcases/consistency/test_consistency.py::test_consistency[192.168.123.12-share-cephfs-default] PASSED [ 84%]
testcases/mount/test_mount.py::test_mount[192.168.123.11-share-cephfs-default] PASSED [ 87%]
testcases/mount/test_mount.py::test_mount[192.168.123.10-share-cephfs-default] PASSED [ 90%]
testcases/mount/test_mount.py::test_mount[192.168.123.12-share-cephfs-default] PASSED [ 93%]
```

When I created test_mount, it was the original sanity test which mounted all the public ip addresses to make sure they were working fine. This has been since been done by the sanity tests and the mount test is now more of an io test. 
I wanted to change the test_mount to run the test only on the first ip address instead of all the ip addresses. This means that the parameter generator function will no longer be similar between sanity test(which should still check all ip addresses) and the mount test(which should be renamed).

2023-11-14 21:05 UTC, spuiuk commented on testcases/consistency/test_consistency.py
> +    "ipaddr,share_name", testhelper.generate_mount_check(test_info_file)
Can you please leave the test_mount generator function separate and return only the first ip address along with the exported shares.

2023-11-22 10:22 UTC, Shwetha-Acharya commented
/retest all

2023-11-23 11:36 UTC, Shwetha-Acharya commented on conftest.py
> +#!/usr/bin/env python3
done.

2023-11-23 11:41 UTC, Shwetha-Acharya commented on testcases/consistency/test_consistency.py
> +test_info_file = os.getenv("TEST_INFO_FILE")
Done!

2023-11-23 11:50 UTC, Shwetha-Acharya commented on conftest.py
> +    return test_dir
> Will this code below the return be executed?

yes, return is executed. The setup_mount call will be replaced by the created testdir during the execution

2023-11-23 16:18 UTC, Shwetha-Acharya commented
I can address next comments, if we are sure we want to go ahead with fixture approach or not

2023-11-30 14:39 UTC, Shwetha-Acharya commented on testcases/consistency/test_consistency.py
> +    "ipaddr,share_name", testhelper.generate_mount_check(test_info_file)
Kept all the generator functions as is

2023-11-30 14:40 UTC, Shwetha-Acharya commented on conftest.py
> +    return test_dir
> Should you instead use yield in the setup function? https://docs.pytest.org/en/latest/how-to/fixtures.html#teardown-cleanup-aka-fixture-finalization

Done!

2023-11-30 14:40 UTC, Shwetha-Acharya commented
As per our discussion, went ahead with fixture approach and addressed all the comments and suggestions

2023-12-01 05:25 UTC, Shwetha-Acharya commented
/retest all

2023-12-01 06:38 UTC, Shwetha-Acharya commented
@spuiuk Please notice my recent reply on your comment of  "run the test only on the first ip address instead of all the ip addresses." 

I am yet to handle the case of premounted share in this PR, based on your reply to my comment, I can handle that case as well

2023-12-01 12:42 UTC, spuiuk reviewed
Some changes requested. 
Also, to complete this patch we need to also handle premounted shares.

2023-12-01 12:42 UTC, spuiuk commented on testcases/mount/conftest.py
> +        test_info = testhelper.read_yaml(test_info_file)
Why not set test_info in global variable?

2023-12-01 12:42 UTC, spuiuk commented on testcases/mount/conftest.py
> +        test_dir = os.path.join(mount_point, "mount_test")
mount_point as returned by testhelper.get_tmp_mount_point() is of type Path. you could simply do 
test_dir = mount_point / "mount_test"

2023-12-01 12:42 UTC, spuiuk commented on testcases/mount/conftest.py
> +        os.makedirs(test_dir, exist_ok=True)
test_dir.mkdir()

2023-12-01 12:42 UTC, spuiuk commented on testcases/mount/conftest.py
> +        test_dir = os.path.join(mount_point, "mount_test")
you will also need
from pathlib import Path
above

2023-12-01 12:42 UTC, spuiuk commented on testcases/mount/conftest.py
> +    test_info = testhelper.read_yaml(test_info_file)
global test_info instead of loading the file everytime.

2023-12-01 12:42 UTC, spuiuk commented on testcases/mount/test_mount_dbm.py
> +def test_dbm_consistency(setup_mount):
parameter type.

2023-12-01 12:42 UTC, spuiuk commented on testcases/mount/test_mount_dbm.py
> +    base = Path(setup_mount) / "dbm-consistency"
use Path in parameter type above and you don't need to do this.

2023-12-01 12:42 UTC, spuiuk commented on testcases/mount/test_mount_io.py
> +def _check_io_consistency(test_dir: str) -> None:
Use Path instead of str for any path component.

2023-12-01 12:42 UTC, spuiuk commented on testcases/mount/test_mount_io.py
> +        base = Path(test_dir) / "test_io_consistency"
same as above. Stick to Path and you don't have to do this.

2023-12-01 12:42 UTC, spuiuk commented on testcases/mount/conftest.py
> +        os.rmdir(tmp_root)
Can you also use mount_point.rmdir() and tmp_root.rmdir() here. I seem to have missed it in my earlier patch and this is a good time to fix it.

2023-12-05 12:30 UTC, Shwetha-Acharya commented on testcases/mount/conftest.py
> +    test_info = testhelper.read_yaml(test_info_file)
Same query https://github.com/samba-in-kubernetes/sit-test-cases/pull/48  applies here as well

2023-12-05 12:55 UTC, Shwetha-Acharya commented on testcases/mount/conftest.py
> +        os.rmdir(tmp_root)
Done!

2023-12-05 12:56 UTC, Shwetha-Acharya commented on testcases/mount/test_mount_io.py
> +def _check_io_consistency(test_dir: str) -> None:
Done!

2023-12-05 12:56 UTC, Shwetha-Acharya commented on testcases/mount/test_mount_dbm.py
> +    base = Path(setup_mount) / "dbm-consistency"
Done!

2023-12-05 12:56 UTC, Shwetha-Acharya commented on testcases/mount/test_mount_dbm.py
> +def test_dbm_consistency(setup_mount):
Done!

2023-12-05 12:56 UTC, Shwetha-Acharya commented on testcases/mount/conftest.py
> +        os.makedirs(test_dir, exist_ok=True)
Done!

2023-12-05 12:56 UTC, Shwetha-Acharya commented on testcases/mount/conftest.py
> +        test_dir = os.path.join(mount_point, "mount_test")
Done!

2023-12-06 19:43 UTC, spuiuk requested changes

2023-12-06 19:43 UTC, spuiuk commented on testcases/mount/test_mount_stress.py
>      )
Can you please leave the stress tests the same for now. I intended to ask you to reduce the number of tests here as it takes a long time at the moment. We could reduce the number of tests we run to a single test with 20 clients - I mean if it works with 20 clients, it will probably also work with 5 clients.  We can do this with a later PR.

2023-12-06 19:52 UTC, spuiuk requested changes

2023-12-06 19:52 UTC, spuiuk commented on testcases/mount/conftest.py
> +        sharename = test_info["exported_sharenames"][0]
I just went through this code again. This will only test one sharename listed. 

The intention is to test with the first listed ip address but test all sharenames which have been provided. The multiple sharenames are needed because we could have different types of volumes in them. eg: Replicated and disperse volumes in gluster. This would only test the first sharename listed ie. replicated. 

This approach is a NAK from me.

2023-12-06 19:53 UTC, spuiuk commented on testcases/mount/conftest.py
> +        test_info = testhelper.read_yaml(test_info_file)
This approach is a NAK

Please consider https://github.com/samba-in-kubernetes/sit-test-cases/pull/38#discussion_r1417905545

2023-12-07 06:27 UTC, Shwetha-Acharya commented on testcases/mount/test_mount_stress.py
>      )
I have not made any changes in stress test as of now, only setup mount is added and hence the indentation is changed by black.

I can add another PR suggested by you.

2023-12-07 07:10 UTC, spuiuk commented on testcases/mount/test_mount_stress.py
>      )
sorry. yes. that is true

2023-12-07 10:23 UTC, Shwetha-Acharya commented on testcases/mount/conftest.py
> +        test_info = testhelper.read_yaml(test_info_file)
sure, in that case, we might have to import test_info inside sit-test-cases/test-helper/testheper.py from sit-test-cases/mount/conftest.py
from mount.conftest import test_info

Is that what you are suggesting?

2023-12-07 10:29 UTC, Shwetha-Acharya commented on testcases/mount/conftest.py
> +        sharename = test_info["exported_sharenames"][0]
Addressed this by making use of only first ipaddr, let me if this works for you.

premounted shares and global test-info are yet to be handled

2023-12-07 15:56 UTC, spuiuk commented on testcases/mount/conftest.py
> +        test_info = testhelper.read_yaml(test_info_file)
No. We don't need to use global variables within the testhelper module.

Please follow the approach used in other tests or even the same test. If adding fixtures require that we use global variables in the testhelper module then I am inclined to NAK the whole patch series.

2023-12-07 17:21 UTC, Shwetha-Acharya commented on testcases/mount/conftest.py
> +        test_info = testhelper.read_yaml(test_info_file)
If we are to follow the same approach used in other existing tests, we are already on a right track 

existing approach in main branch: https://github.com/samba-in-kubernetes/sit-test-cases/blob/main/testcases/mount/test_mount.py
current change:https://github.com/samba-in-kubernetes/sit-test-cases/pull/38/commits/70a9c0d39663044fe479960157d77cc9d2d05fed#diff-89e5c02bddad8e8834266d39664b3546c3206ba12c31b972711866e58d51a978

test_info is already a global variable in conftest.py 
Seems we were looking at two different things. I was thinking you did not want me to pass test_info_file to testhelper.read_yaml(test_info_file)

2023-12-07 17:32 UTC, spuiuk commented on testcases/mount/conftest.py
> +        test_info = testhelper.read_yaml(test_info_file)
Ahh yes. This is better. There are still a few minor changes I would like you to do and will provide a more detailed review tomorrow.

2023-12-07 17:35 UTC, spuiuk commented on testcases/consistency/test_consistency.py
> +    "ipaddr,share_name", testhelper.generate_mount_check(test_info_file)
several chanes have been made later which address this issue of generator functions for this particular test. Setting this particular change request to resolved.

2023-12-07 17:36 UTC, spuiuk commented on testcases/mount/conftest.py
> +        sharename = test_info["exported_sharenames"][0]
The issue of testing all shares has been addressed with the latest version.

2023-12-07 17:43 UTC, spuiuk requested changes
some minor changes. The rest looks good. 

You can also go ahead with re-adding tests for pre-mounted shares after making those changes.

Thanks.

2023-12-07 17:43 UTC, spuiuk commented on testcases/mount/conftest.py
> +    first_ipaddr: str, share_name: str
Would you please consider changing the parameter name to ipaddr instead of first_ipaddr. The setup_mount simply mounts the share_name at a ip address and doesn't need to know if this is the first ipaddr. This will only cause confusion for those reading the code later.

This will also require changes below.

2023-12-07 17:43 UTC, spuiuk commented on testcases/mount/conftest.py
> +            testhelper.read_yaml(test_info_file), share_name
just use the global test_info instead of calling testhelper.read_yaml() here.

2023-12-07 17:43 UTC, spuiuk commented on testcases/mount/test_mount_dbm.py
> +@pytest.mark.parametrize("first_ipaddr,share_name", generate_mount_check())
consider renaming first_ipaddr to ipaddr as requested above.

2023-12-07 17:43 UTC, spuiuk commented on testcases/mount/test_mount_io.py
> +@pytest.mark.parametrize("first_ipaddr,share_name", generate_mount_check())
consider renaming first_ipaddr to ipaddr as requested above.

2023-12-07 17:43 UTC, spuiuk commented on testcases/mount/test_mount_stress.py
> +@pytest.mark.parametrize("first_ipaddr,share_name", generate_mount_check())
consider renaming first_ipaddr to ipaddr as requested above.

2023-12-11 07:19 UTC, Shwetha-Acharya commented on testcases/mount/test_mount_stress.py
> +@pytest.mark.parametrize("first_ipaddr,share_name", generate_mount_check())
Done!

2023-12-11 07:19 UTC, Shwetha-Acharya commented on testcases/mount/test_mount_dbm.py
> +@pytest.mark.parametrize("first_ipaddr,share_name", generate_mount_check())
Done!

2023-12-11 07:19 UTC, Shwetha-Acharya commented on testcases/mount/conftest.py
> +            testhelper.read_yaml(test_info_file), share_name
Done!

2023-12-11 07:19 UTC, Shwetha-Acharya commented on testcases/mount/conftest.py
> +    first_ipaddr: str, share_name: str
Done!

2023-12-11 10:34 UTC, Shwetha-Acharya commented
@spuiuk  as sit environment is not adding any premounted share value inside test-info created by it, I have added logic to ignore premounted share test, if there are no pre mounted shared in test-info fie.

This is useful if any user want to run the tests without the value of premounted_share manually as well

2024-01-01 19:05 UTC, spuiuk requested changes

2024-01-01 19:10 UTC, spuiuk commented
Please consider the following suggestions  for a future PR. These aren't a result of the changes in this PR but will be nice to have for this test.
1) in _run_dbm_consistency_checks() and _check_io_consistency(), the mkdir call should have parents=False. I don't see why we should have this option set to True. A missing parent directory should be treated as an error.
2) _perform_file_operations() should perform the file operations in a sub directory to allow for easier clean up.

2024-01-01 19:28 UTC, spuiuk commented
> @spuiuk sit environment is not adding any premounted share value inside test-info created by it:
> 

> So, inorder to resolve this, I have added logic to ignore premounted share test, if there are no premounted shares in test-info fie.
> 
> This logic to skip is useful even if any user wants to manually run the tests without the value of premounted shares inside the test_info file

This is fine in my opinion. pytest skips the empty tests and it isn't considered an error. I have requested you to remove this logic from the code from my code review which I did earlier.

The premounted shares section is for use with Windows clients where we cannot use mount the shares for the client. In such cases, we need to consider pre-mounted locations to run the tests on. In such cases, we will see the opposite where Skipped messages will be seen on tests which expect to perform the cifs_mounts. eg:  test_check_mnt_stress(), test_dbm_consistency(), test_check_io_consistency()

2024-01-02 06:42 UTC, Shwetha-Acharya commented on testcases/mount/test_mount_stress.py
> +    test_dir: Path, pre_mounted_shares_available: bool
Done

2024-01-02 06:42 UTC, Shwetha-Acharya commented on testcases/mount/test_mount_io.py
> +    test_dir: Path, pre_mounted_shares_available: bool
Done

2024-01-02 06:42 UTC, Shwetha-Acharya commented on testcases/mount/test_mount_dbm.py
> +    if not pre_mounted_shares_available:
Done

2024-01-02 06:42 UTC, Shwetha-Acharya commented on testcases/mount/conftest.py
> +def pre_mounted_shares_available(test_info):
Done

2024-01-02 06:43 UTC, Shwetha-Acharya commented
> Please consider the following suggestions for a future PR. These aren't a result of the changes in this PR but will be nice to have for this test.
> 
> 1. in _run_dbm_consistency_checks() and _check_io_consistency(), the mkdir call should have parents=False. I don't see why we should have this option set to True. A missing parent directory should be treated as an error.
> 2. _perform_file_operations() should perform the file operations in a sub directory to allow for easier clean up.

I will take a look on it after this PR id merged. Else there can be a lot of merge conflicts.

2024-01-02 10:44 UTC, spuiuk commented
/retest centos-ci/xfs

2024-01-03 12:42 UTC, spuiuk commented on testcases/mount/test_mount_dbm.py
> +def test_dbm_consistency(setup_mount: Path) -> None:
WRT, calling a fixture setup_mount and it receiving the parameters from pytest.mark.parametrize(). 
I can confirm that this is working as expected. I am however unable to find any documentation explaining that this is how it is support to work. If you have a link, can you please point me to their web page which describes this operation.

Thanks

2024-01-03 12:48 UTC, spuiuk requested changes

2024-01-03 12:48 UTC, spuiuk commented on testcases/mount/test_mount_stress.py
> +    test_dir: Path, pre_mounted_shares_available: bool
Sorry, this is unresolved. the parameter here is not required.

2024-01-03 13:12 UTC, Shwetha-Acharya commented on testcases/mount/test_mount_stress.py
> +    test_dir: Path, pre_mounted_shares_available: bool
Addressed

2024-01-03 13:45 UTC, Shwetha-Acharya commented on testcases/mount/test_mount_dbm.py
> +def test_dbm_consistency(setup_mount: Path) -> None:
Basically concept of fixtures and parameterize are covered separately in official docs.
Based on their properties, the code is working as expected:

Refer: 

- https://docs.pytest.org/en/7.1.x/how-to/fixtures.html
- https://docs.pytest.org/en/7.3.x/how-to/parametrize.html


Digging deeper I found some instances of such usage:
Refer the example under the title `Parametrization with multiple fixtures` in https://docs.pytest.org/en/latest/example/parametrize.html#apply-indirect-on-particular-arguments

2024-01-05 15:08 UTC, spuiuk commented on testcases/mount/test_mount_dbm.py
> +def test_dbm_consistency(setup_mount: Path) -> None:
So this is a valid way to do it but it isn't documented.
https://github.com/pytest-dev/pytest/discussions/11775

Just for clarity sake, can you please modify the code to use the indirect approach ie. indirect=True
https://docs.pytest.org/en/latest/example/parametrize.html#indirect-parametrization
We should receive a tuple at request.param which can be mapped to ipaddr and share_name and the rest of the code can remain the same.

2024-01-08 07:13 UTC, Shwetha-Acharya commented on testcases/mount/test_mount_dbm.py
> +def test_dbm_consistency(setup_mount: Path) -> None:
@spuiuk I am not sure if we want to use indirect here.
In our case generate_mount_check is not a fixture. We are simply using the concept of parametrize on a normal function generate_mount_check().

If you see https://docs.pytest.org/en/latest/example/parametrize.html#indirect-parametrization indirect is always used while calling the fixtures inside parametrize. 

I am wondering if are to make  generate_mount_check a fixture inorder to use indirect, which is not looking very right to me.

Please share your views.

2024-01-08 22:26 UTC, spuiuk commented on testcases/mount/test_mount_dbm.py
> +def test_dbm_consistency(setup_mount: Path) -> None:
setup_mount() is the fixture we wont to run to run setup/teardown for the test.  generate_mount_check() is used to simply generate the list of arguments required for the setup fixture. So we can use it in the same manner as the example given at 
https://docs.pytest.org/en/latest/example/parametrize.html#indirect-parametrization

I believe the code will be similar to the following

The fixture:
```
 @pytest.fixture
 def setup_mount(
-    ipaddr: str, share_name: str
+    request: pytest.FixtureRequest,
 ) -> typing.Generator[Path, None, None]:
+    ipaddr, share_name = request.param
     flag_mounted: bool = False
```

and the tests in a manner similar to
```
-@pytest.mark.parametrize("ipaddr,share_name", generate_mount_check())
+@pytest.mark.parametrize("setup_mount", generate_mount_check(), indirect=True)
 def test_dbm_consistency(setup_mount: Path) -> None:
     base = setup_mount / "dbm-consistency"
```

2024-01-09 06:44 UTC, Shwetha-Acharya commented on testcases/mount/test_mount_dbm.py
> +def test_dbm_consistency(setup_mount: Path) -> None:
okay, got it now

2024-01-09 11:26 UTC, spuiuk approved these changes
ACK

Confirmed that the CI tests for xfs only fail at smb2.create which is a known failure because of selinux issues. All other tests pass as expected.

2024-01-09 12:25 UTC, synarete approved these changes
lgtm

2024-01-10 10:40 UTC, merged