Pytest
samba-in-kubernetes/sit-test-cases pull request #5
Opened 2023-06-19 16:18 UTC by spuiuk

Use pytest as a runner instead of the shell scripts at the moment.

2023-06-21 13:55 UTC, spuiuk commented
retest this please

2023-06-21 20:07 UTC, spuiuk commented
https://jenkins-samba.apps.ocp.cloud.ci.centos.org/job/samba_gluster-integration-test-cases/150/consoleText

Testing Output:

```
============================= test session starts ==============================
platform linux -- Python 3.6.8, pytest-3.4.2, py-1.5.3, pluggy-0.6.0 -- /usr/libexec/platform-python
cachedir: .pytest_cache
rootdir: /root/samba-integration-tests, inifile:
collecting ... collected 51 items

testcases/mount/test_mount.py::test_mount PASSED                         [  1%]
testcases/consistency_check/test_consistency_check.py::test_consistency[gluster-vol-replicate] PASSED [  3%]
testcases/consistency_check/test_consistency_check.py::test_consistency[gluster-vol-disperse] PASSED [  5%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.rw] PASSED [  7%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.read] PASSED [  9%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.bench-oplock] PASSED [ 11%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.check-sharemode] PASSED [ 13%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.compound_find] PASSED [ 15%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.connect] PASSED [ 17%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.credits] PASSED [ 19%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.deny] PASSED [ 21%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.lock] PASSED [ 23%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.mangle] PASSED [ 25%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.maximum_allowed] PASSED [ 27%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.mkdir] PASSED [ 29%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.notify-inotify] PASSED [ 31%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.rename] PASSED [ 33%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.sdread] PASSED [ 35%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.secleak] PASSED [ 37%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.session-id] PASSED [ 39%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.sharemode] PASSED [ 41%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.tcon] PASSED [ 43%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.winattr] PASSED [ 45%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.durable-open-disconnect] PASSED [ 47%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.openattr] PASSED [ 49%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.session] PASSED [ 50%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-replicate-smb2.create] FAILED [ 52%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.rw] PASSED [ 54%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.read] PASSED [ 56%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.bench-oplock] PASSED [ 58%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.check-sharemode] PASSED [ 60%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.compound_find] PASSED [ 62%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.connect] PASSED [ 64%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.credits] PASSED [ 66%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.deny] FAILED [ 68%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.lock] PASSED [ 70%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.mangle] PASSED [ 72%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.maximum_allowed] PASSED [ 74%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.mkdir] PASSED [ 76%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.notify-inotify] PASSED [ 78%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.rename] PASSED [ 80%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.sdread] PASSED [ 82%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.secleak] PASSED [ 84%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.session-id] PASSED [ 86%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.sharemode] PASSED [ 88%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.tcon] PASSED [ 90%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.winattr] PASSED [ 92%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.durable-open-disconnect] PASSED [ 94%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.openattr] PASSED [ 96%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.session] PASSED [ 98%]
testcases/smbtorture/test_smbtorture.py::test_smbtorture[gluster-vol-disperse-smb2.create] PASSED [100%]

=================================== FAILURES ===================================
______________ test_smbtorture[gluster-vol-replicate-smb2.create] ______________

share_name = 'gluster-vol-replicate', test = 'smb2.create'

    @pytest.mark.parametrize("share_name,test", generate_smbtorture_tests(os.getenv('TEST_INFO_FILE')))
    def test_smbtorture(share_name, test):
        ret = smbtorture(share_name, test, output)
        if ret == False:
            print("--Output Start--")
            with open(output) as f:
                print(f.read())
            print("--Output End--")
>           assert False
E           assert False

testcases/smbtorture/test_smbtorture.py:83: AssertionError
----------------------------- Captured stdout call -----------------------------
--Output Start--
Command: /bin/smbtorture --fullname --option=torture:progress=no --option=torture:sharedelay=100000 --option=torture:writetimeupdatedelay=500000 --format=subunit --target=samba3 --user=test1%x //192.168.123.10/gluster-vol-replicate smb2.create 2>&1|/usr/bin/python3 /root/samba-integration-tests/testcases/smbtorture/selftest/filter-subunit --fail-on-empty --prefix='samba3.' --expected-failures=/root/samba-integration-tests/testcases/smbtorture/selftest/knownfail --expected-failures=/root/samba-integration-tests/testcases/smbtorture/selftest/knownfail.d --flapping=/root/samba-integration-tests/testcases/smbtorture/selftest/flapping --flapping=/root/samba-integration-tests/testcases/smbtorture/selftest/flapping.d --flapping=/root/samba-integration-tests/testcases/smbtorture/selftest/flapping.gluster|/usr/bin/tee -a /tmp/tmp_file_0|/usr/bin/python3 /root/samba-integration-tests/testcases/smbtorture/selftest/format-subunit >/dev/null

smbtorture 4.19.0pre1-UNKNOWN
Using seed 1687372114
time: 2023-06-21 18:28:34.328546Z
progress: 17
test: samba3.smb2.create.gentest
time: 2023-06-21 18:28:34.328858Z
time: 2023-06-21 18:28:34.527605Z
xfail: samba3.smb2.create.gentest [
Exception: (../../source4/torture/smb2/create.c:167) Incorrect status NT_STATUS_OK - should be NT_STATUS_INVALID_PARAMETER

]
te [...]

2023-06-23 16:30 UTC, spuiuk commented
This is a long list of patches but fortunately the changes in each are short so should be easy to review. 
I have several more changes to go through but will push them in shorter PRs in the future.

With this change, we have removed all logic for printing output in our code and instead use pytest to do it for us. The output style is shown in an earlier comment.

2023-06-26 07:24 UTC, anoopcs9 requested changes

2023-06-26 07:24 UTC, anoopcs9 commented on Makefile
> +PATH := ${PATH}:/usr/local/bin
```suggestion
PATH := $(PATH):/usr/local/bin
```

2023-06-26 07:24 UTC, anoopcs9 commented on testhelper/testhelper.py
> +def get_mount_parameter(test_info, share, combonum=0):
```suggestion
def get_mount_parameters(test_info, share, combonum=0):

2023-06-26 07:24 UTC, anoopcs9 commented on testcases/consistency_check/test_consistency_check.py
> +        pytest.fail("Error when open/write/read/close")
Updated failure message may not add any value compared to existing one.

2023-06-26 08:39 UTC, spuiuk commented on Makefile
> +export PYTHONPATH TEST_INFO_FILE
We need the PATH just for executing pytest. We don't really need it when tests are actually executed but it may still be a good idea to export it.

2023-06-26 12:55 UTC, spuiuk commented on testcases/consistency_check/test_consistency_check.py
> +        pytest.fail("Error when open/write/read/close")
Actually the code here results in us checking for two separate exceptions. 
https://github.com/samba-in-kubernetes/sit-test-cases/pull/5/files/45b206682dedfe2304969e941575ebd41be5bacc..580e2783ac2d749c89ed46def027ab3be928a154#diff-ee0894631a7fe2da4709f53cdf2ca7c1112d4174140ebeccb7d59fc3d2b1cfe6

One is the assertion error when the file contents do not match and 
the second where any of the other operations fail.  The second is a catchall which will be more useful once we add more assertions in the helper code.

2023-06-27 07:37 UTC, anoopcs9 commented on testcases/consistency_check/run_test
> +test_consistency_check.py
Following the pattern used elsewhere don't we just name it as _consistency_ and not _consistency_check_?

2023-06-27 07:39 UTC, anoopcs9 reviewed
I just have a naming suggestion.

2023-06-27 07:39 UTC, anoopcs9 commented on testcases/consistency_check/test_consistency_check.py
> +        pytest.fail("Error when open/write/read/close")
Ok.

2023-06-27 10:09 UTC, spuiuk commented on testcases/consistency_check/run_test
> +test_consistency_check.py
Yeah. I was in two minds about it already. I have renamed the test and pushed it as a new commit.

2023-06-27 11:11 UTC, anoopcs9 reviewed
Why do we have symlinks named _run_test_ in each category of testcases?
```
lrwxrwxrwx. 1 19  testcases/consistency/run_test -> test_consistency.py
lrwxrwxrwx. 1 13  testcases/mount/run_test -> test_mount.py
lrwxrwxrwx. 1 18  testcases/smbtorture/run_test -> test_smbtorture.py
```

2023-06-27 12:39 UTC, spuiuk commented
> Why do we have symlinks named _run_test_ in each category of testcases?
> 
> ```
> lrwxrwxrwx. 1 19  testcases/consistency/run_test -> test_consistency.py
> lrwxrwxrwx. 1 13  testcases/mount/run_test -> test_mount.py
> lrwxrwxrwx. 1 18  testcases/smbtorture/run_test -> test_smbtorture.py
> ```

These are artifacts from the earlier test runner which would call run_test in each directory. We don't need it with pytest but I have left it for now. We can remove them with a trivial patch at a later date.

2023-06-30 08:42 UTC, anoopcs9 approved these changes
> > Why do we have symlinks named _run_test_ in each category of testcases?
> > ```
> > lrwxrwxrwx. 1 19  testcases/consistency/run_test -> test_consistency.py
> > lrwxrwxrwx. 1 13  testcases/mount/run_test -> test_mount.py
> > lrwxrwxrwx. 1 18  testcases/smbtorture/run_test -> test_smbtorture.py
> > ```
> 
> These are artifacts from the earlier test runner which would call run_test in each directory. We don't need it with pytest but I have left it for now. We can remove them with a trivial patch at a later date.

Let's not forget it moving forward.

2023-06-30 13:25 UTC, spuiuk commented
@anoopcs9 , I decided to remove the run_test symlinks as part of this set of changes itself.

2023-06-30 17:28 UTC, anoopcs9 approved these changes
> @anoopcs9 , I decided to remove the run_test symlinks as part of this set of changes itself.

Thanks.

2023-07-03 08:57 UTC, spuiuk commented
Force merging as smbtorture tests fail at the moment.

2023-07-03 08:57 UTC, merged