testhelper/smbclient.py: use smbprotocol python module
samba-in-kubernetes/sit-test-cases pull request #84
Opened 2024-06-18 20:54 UTC by spuiuk

pysmb only support SMB2.0 version. The samba-container defaults to using SMB2.1 protocol and we are unable to use pysmb to connect to the samba server. This is a major issue.

The smbprotocol python module avoids this problem.

2024-06-26 15:17 UTC, phlogistonjohn commented on testhelper/smbclient.py
> +        self.client = {
Minor nitpick: I was skimming though the code and saw something like `smbclient.open_file(path, mode=xyz, **self.client)` and was confused and went back to see that a client was indeed a dict. I suggest renaming this var something like `client_params` or `client_options` for clarity.

2024-06-26 17:41 UTC, spuiuk commented on testhelper/smbclient.py
> +        self.client = {
Thanks. Fixed it.

2024-06-27 06:30 UTC, synarete commented on testhelper/smbclient.py
> +                    data = writeobj.read(4096)
Why suck small chunk size? This is inefficient. Modern machines should have no problem to do it with 1M, 2M or 4M chunk sizes.

2024-06-27 06:30 UTC, synarete commented on testhelper/smbclient.py
> +        except SMBException as error:
This whole read-write in chunks logic should be separated into helper function. Same hold for lines 93-99 above. In addition, the `if len(data) == 0` may be removed as it is already handled implicitly by the following `while` loop.

2024-06-27 14:52 UTC, spuiuk commented on testhelper/smbclient.py
> +        except SMBException as error:
I have split out the read-write cycle into a helper function.
The if condition is needed to break out of the while loop which reads data before writing to the fd.

I have uploaded the new set of code.  Can you please take a look. Thanks.

2024-06-27 15:08 UTC, synarete approved these changes
Looks better. See nit comment.

2024-06-27 15:08 UTC, synarete commented on testhelper/smbclient.py
> +rw_chunk_size = 1 << 21  # 21MB
Nit: 2MB (not 21)

2024-06-27 15:28 UTC, spuiuk commented on testhelper/smbclient.py
> +rw_chunk_size = 1 << 21  # 21MB
fixed.

2024-06-28 06:14 UTC, anoopcs9 requested changes

2024-06-28 11:44 UTC, Shwetha-Acharya reviewed
except for the line 11 change, commented about already, rest of the things look good to me

2024-06-28 13:04 UTC, spuiuk commented on testhelper/smbclient.py
>      """Use pysmb to access the SMB server"""
Thanks - Good catch. Have fixed it in the latest submission.

2024-06-28 14:01 UTC, anoopcs9 approved these changes

2024-06-28 14:39 UTC, merged